import tsParser from "@typescript-eslint/parser";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tailwindCanonicalClasses from "eslint-plugin-tailwind-canonical-classes";
import { defineConfig, globalIgnores } from "eslint/config";
import globals from "globals";

const eslintConfig = defineConfig([
	...nextVitals,
	...nextTs,
	...tailwindCanonicalClasses.configs["flat/recommended"],
	{
		rules: {
			"tailwind-canonical-classes/tailwind-canonical-classes": [
				"warn",
				{
					cssPath: "./app/globals.css"
				}
			],
			"@next/next/no-img-element": "off",
			"@typescript-eslint/no-explicit-any": "warn"
		}
	},
	{
		files: ["**/*.{ts,tsx,js,jsx}"],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				ecmaFeatures: { jsx: true }
			},
			globals: {
				...globals.browser
			}
		}
	},
	{
		settings: {
			react: { version: "19.2.5" }
		}
	},
	// Override default ignores of eslint-config-next.
	globalIgnores([
		// Default ignores of eslint-config-next:
		".next/**",
		"out/**",
		"build/**",
		"next-env.d.ts",
		// Generated by Prisma:
		"prisma/generated/**"
	])
]);

export default eslintConfig;
